<a href="https://colab.research.google.com/github/sodaaw/torchcode/blob/main/torchpractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

입력 텐서 -> (shape 확인) -> 연산 (어떤 dim으로? keepdim 할지말지?) -> 출력 텐서

In [2]:
import torch

In [3]:
# 0으로 채운 텐서
print(torch.zeros(3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [4]:
# 1로 채운 텐서
print(torch.ones(3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [5]:
# 랜덤한 숫자로 채운 텐서
print(torch.randn(3,4))

tensor([[-0.2585,  0.8780,  1.8292, -1.0489],
        [-0.5638,  2.0356,  0.2628,  0.9825],
        [ 0.9694,  2.4965,  1.3951, -0.3314]])


In [6]:
# 0부터 n까지
print(torch.arange(10))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


shape 다루기

In [8]:
# shape 출력하기
x = torch.randn(3,4)
x.shape

torch.Size([3, 4])

In [9]:
# reshape - shape를 바꾸기. a*b = c*d 일때만 가능함
x = torch.randn(3,4)
x.reshape(2,6).shape

torch.Size([2, 6])

In [17]:
# unsqueeze - 차원 추가
x = torch.randn(3)
print(x)
print(x.shape)

x_unsqueezed_0 = x.unsqueeze(0)

# unsqueeze하니까 껍데기가 하나 더 생김. shape 앞쪽에 3이 추가됨
# add a dimension / expand dims
# 0번 위치에 차원 추가. 그니까 3의 앞쪽 (0번인덱스)에 추가되는 거임
print(x_unsqueezed_0)
x_unsqueezed_0.shape

tensor([-0.0452,  0.5389, -1.0065])
torch.Size([3])
tensor([[-0.0452,  0.5389, -1.0065]])


torch.Size([1, 3])

In [19]:
x = torch.randn(3)
print(x)
print(x.shape)

x_unsqueezed_1 = x.unsqueeze(1)

# 이번엔 1번 위치에 차원 추가 -> 3의 뒤쪽에 추가됨
# 안쪽에 하나씩 껍데기가 생김
print(x_unsqueezed_1)
x_unsqueezed_1.shape

tensor([ 0.2032, -0.9999, -1.6621])
torch.Size([3])
tensor([[ 0.2032],
        [-0.9999],
        [-1.6621]])


torch.Size([3, 1])

In [21]:
# 반대로 squeeze의 경우 차원을 제거함.
x = torch.randn(1,3)

# 0번 차원을 제거해달라는 뜻
# 근데 여기서 0번 차원 크기가 1이면 제거되고, 1이 아니면 무시됨.
# x가 (2, 3)이었다면 무시되었을 것임!
x.squeeze(0).shape

torch.Size([3])

In [23]:
# permute - 텐서 순서 바꾸기
x = torch.randn(2,3,4)

# 0번은 그대로, 2번을 1번 자리로, 1번을 2번 자리로 바꾸기.
# ex. 이미지 텐서가 (배치, 높이, 너비, 채널)인데 (배치, 채널, 높이, 너비)로 바꾸고 싶다. 이럴 때 사용
x.permute(0, 2, 1).shape

torch.Size([2, 4, 3])

연산 관련

# dim=0 0번차원 (행방향)합산. 열 끼리 더함

# dim=1 1번차원 (열방향)합산. 행끼리 더함

# "0열, 1행"

In [24]:
x = torch.tensor(
    [[1., 2., 3.],
     [4., 5., 6.]]
)
# 열끼리 더한다.
# 1열 2열 3열 -> 5, 7, 9
x.sum(dim=0)

tensor([5., 7., 9.])

In [25]:
# 행끼리 더한다.
# 1행
# 2행
# 3행
# 1+2+3, 4+5+6
x.sum(dim=1)

tensor([ 6., 15.])

In [29]:
# 열끼리 평균.
# 1열, 2열, 3열
# 1+4 / 2 ...
x.mean(dim=0).values

# 각 열에서 제일 큰값.
# 1열에서 max, 2열에서 max, ...
x.max(dim=0).values

tensor([4., 5., 6.])

In [27]:
# @ 는 행렬곱. weighted sum에 사용됨!
# (3*4) * (4*5) = (3*5)
a = torch.randn(3,4)
b = torch.randn(4,5)
(a @ b).shape

torch.Size([3, 5])

In [28]:
# 그냥 * 하면 원소별로 곱함
# 같은 위치에 있는 애들끼리 곱해줌. shape는 그대로!!
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])
a * b

tensor([ 4., 10., 18.])

한 cycle동안 학습

In [31]:
import torch
import torch.nn as nn

# 모델 정의 (입력 3개 → 출력 1개짜리 간단한 모델)
model = nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
loss_fn = nn.MSELoss()

# 가짜 데이터
x = torch.randn(5, 3)   # 입력 5개, 특성 3개
y = torch.randn(5, 1)   # 정답 5개


#------------------------------


# 학습모드. 지금부터 학습할거야
model.train()

# 데이터를 batch 단위로 하나씩 가져옴
# x는 입력, y는 출력
for x, y in dataloader:
  # 이전 batch의 gradient를 초기화함
  optimizer.zero_grad()

  # 모델에 입력값 넣고 출력값 output에 저장
  output = model(x)

  # 정답이랑 비교해서 Loss 계산
  loss = loss_fn(output, y)

  # gradient 계산
  loss.backward()

  # 계산된 gradient로 실제 가중치 업데이트
  optimizer.step()

# 학습 끝나고 test시에는 gradient 계산 끔!
model.eval()
with torch.no_grad():
  output = model(x_test)

NameError: name 'dataloader' is not defined